Models/Appointment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DentistApp.Models
{
    public class Appointment
    {
        [Key]
        public int Id { get;set; }
        [Required]
        [Display(Name = "Patient-Name")]
        public string Name { get;set; }
        [Required]
        // [DataType(DataType.EmailAddress)]
        public string Email { get;set; }
        [Required]
        public int Age { get;set; }
        [Required]
        public DateTime Date { get;set; }
        [Required]
        public string Issue { get;set; }
    }
}

Controllers/AppointmentController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DentistApp.Models;
using System.Collections.Generic;
using DentistApp.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;


namespace DentistApp.Controllers
{
    public class AppointmentController : Controller
{
    private readonly ApplicationDbContext _context;

    public AppointmentController(ApplicationDbContext context)
    {
        _context = context;
    }


    [Authorize]
    public IActionResult Main()
    {
        IEnumerable<Appointment> appointments = _context.appointments;
        return View(appointments);
    }


    [Authorize]
    public IActionResult DetailBooking(int? id)
    {
        if (id == null && id == 0)
        {
            return NotFound();
        }
        var Singlebooking = _context.appointments.Find(id);
        if (Singlebooking == null)
        {
            return NotFound();
        }
        return View(Singlebooking);
    }


    [Authorize]
    [HttpGet]
    public IActionResult DeleteBooking(int? id)
    {
        if (id == 0 && id == null)
        {
            return NotFound();
        }
        var bookingToDelete = _context.appointments.Find(id);
        if (bookingToDelete == null)
        {
            return NotFound();
        }
        return View(bookingToDelete);
    }


    [Authorize]
    [HttpPost]
    public IActionResult DeleteBookings(int? id)
    {
        if(id == null && id == 0)
        {
            return NotFound();
        }
        var BookingToDelete = _context.appointments.Find(id);
        if (BookingToDelete != null)
        {
            _context.appointments.Remove(BookingToDelete);
            _context.SaveChanges();
            return RedirectToAction("Main");
        }
        return View();
    }


    [Authorize]
    [HttpGet]
    public IActionResult UpdateBooking(int? id)
    {
        if (id == null && id == 0)
        {
            return NotFound();
        }
        var bookingToUpdate = _context.appointments.Find(id);
        if (bookingToUpdate == null)
        {
            return NotFound();
        }
        return View(bookingToUpdate);
    }


    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult UpdateBooking(Appointment booking)
    {
        if (ModelState.IsValid)
        {
            _context.appointments.Update(booking);
            _context.SaveChanges();
            return RedirectToAction("Main");
        }
        return View(booking);
    }
}

}

Controllers/DashBlogController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DentistApp.Models;
using DentistApp.Data;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;



namespace DentistApp.Controllers
{
    public class DashBlogController : Controller
{
    private readonly ApplicationDbContext _database;

    public DashBlogController(ApplicationDbContext database)
    {
        _database = database;
    }


    [Authorize]
    public IActionResult Dashboard()
    {
        IEnumerable<Blog> AllblogsPosts = _database.blogs;
        return View(AllblogsPosts);
    }


    [Authorize]

    public IActionResult CreateBlog()
    {
        return View();
    }


    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult CreateBlog(Blog data)
    {
        if (ModelState.IsValid)
        {
            _database.blogs.Add(data);
            _database.SaveChanges();
            return RedirectToAction("Dashboard");
        }
        return View(data);
    }


    [Authorize]
    public IActionResult DeleteBlog(int? id)
    {
        if(id == null && id == 0)
        {
            return NotFound();
        }
        var blogPost = _database.blogs.Find(id);
        if (blogPost == null)
        {
            return NotFound();
        }
        return View(blogPost);
    }

    [Authorize]
    [HttpPost]
    public IActionResult DeleteBlogs(int? id)
    {
        if (id == 0 && id == null)
        {
            return NotFound();
        }
        var blogToDelete = _database.blogs.Find(id);
        if (blogToDelete != null)
        {
            _database.blogs.Remove(blogToDelete);
            _database.SaveChanges();
            return RedirectToAction("Dashboard");
        }
        return View(blogToDelete);
    }


    [Authorize]
    public IActionResult DetailBlog(int? id)
    {
        if (id == null && id == 0)
        {
            return NotFound();
        }
        var blogPost = _database.blogs.Find(id);
        if (blogPost == null)
        {
            return NotFound();
        }
        return View(blogPost);
    }

    [Authorize]
    [HttpGet]
    public IActionResult UpdateBlog(int? id)
    {
        if (id == null && id == 0)
        {
            return NotFound();
        }
        var FindingAblog = _database.blogs.Find(id);
        Blog blogPost;
        if (FindingAblog != null)
        {
            blogPost = FindingAblog;
            if (blogPost == null)
            {
                return NotFound();
            }
            return View(blogPost);
        }

        return View(FindingAblog);
    }


    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult UpdateBlog(Blog data)
    {
        if (ModelState.IsValid)
        {
            _database.blogs.Update(data);
            _database.SaveChanges();
            return RedirectToAction("Dashboard");
        }
        return View(data);
    }
}

}

Views/Appointment/DeleteBooking.cshtml
@model DentistApp.Models.Appointment;

@{
    ViewData["Title"] = "Delete-Booking";
}


<div class="container mx-auto max-w-3xl py-20 px-8">
    <h1 class="font-serif text-3xl md:text-4xl pb-4">Delete Booking</h1>
    <h1 class="font-serif text-xl pb-4 underline">
        <a asp-controller="Appointment" asp-action="Main">Return to Home</a>
    </h1>
    <div class="container mx-auto max-w-3xl ">



    <form asp-action="DeleteBookings" method="post" class="mx-auto">
        <input asp-for="Id" class="hidden"/>
        <button type="submit" class="font-serif text-xl pb-4 underline text-red-600">Delete</button>
        @* <h1 class="font-serif text-xl pb-4 underline text-red-600">Delete</h1> *@
    </form>
    <h1 class="font-serif text-xl pb-4 text-blue-600 underline">
        <a asp-controller="Appointment" asp-action="Main">Cancel Delete</a>
    </h1>
</div>

</div>

Views/Appointment/DetailBooking.cshtml
@model DentistApp.Models.Appointment;

@{
    ViewData["Title"] = "Booking-Details";
}


<div class="aboutbg px-8">
        <h1 class="text-center font-serif text-3xl md:text-4xl pb-4 text-white">Booking Details</h1>
    </div>
    <div class="container mx-auto max-w-3xl py-20 px-8">
        <h1 class="font-serif text-xl pb-4 underline">
            <a asp-controller="Appointment" asp-action="Main">Return to Home</a>
        </h1>
        <form class="mx-auto">
            <div class="py-2 grid grid-cols-1 md:grid-cols-2 gap-5">
                <div class="flex flex-col">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" disabled type="text" class="w-full py-2 px-3 border-2 border-gray-700" />
                </div>
                <div class="flex flex-col">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" disabled type="text" class="py-2 px-3 border-2 border-gray-700"/>
                </div>
            </div>
            <div class="py-2 grid grid-cols-1 md:grid-cols-2 gap-5">
                <div class="flex flex-col">
                    <label asp-for="Age"></label>
                    <input asp-for="Age" disabled type="number" class="py-2 px-3 border-2 border-gray-700 w-full" />
                </div>
                <div class="flex flex-col">
                    <label asp-for="Date"></label>
                    <input asp-for="Date" disabled type="datetime" class="py-2 px-3 border-2 border-gray-700 w-full"/>
                </div>
            </div>
            <div class="">
                <label asp-for="Issue"></label>
                <textarea asp-for="Issue" disabled name="" id="" cols="30" rows="10" class="py-2 px-3 border-2 border-gray-700 w-full"></textarea>
            </div>
        </form>
    </div>

Views/Appointment/Main.cshtml
@model IEnumerable<DentistApp.Models.Appointment>


@{
    ViewData["Title"] = "Appointments-Dashboard";
}


<div class="container mx-auto max-w-4xl py-20 px-8">
        <h1 class="font-serif text-3xl md:text-4xl pb-4 pb-10">Dr Chung Admin</h1>
        <div class="pb-20">
            <h1 class="font-serif text-2xl pb-4 pb-2">@Model.Count() <span class="underline">Appointments</span></h1>
            <h1 class="font-serif text-2xl pb-4 pb-10 underline">
                <a asp-controller="DashBlog" asp-action="Dashboard">Blogs Management</a>
            </h1>
        </div>

        <h1 class="font-serif text-2xl pb-4 pb-10 underline">List of Appointments</h1>

        @if (Model.Count() >= 1)
        {
            <table class="table w-full">
                <thead>
                    <tr>
                        <th class="px-4 py-2 text-xl"></th>
                        <th class="px-4 py-2 text-xl">Id</th>
                        <th class="px-4 py-2 text-xl">Name</th>
                        <th class="px-4 py-2 text-xl">Email</th>
                        <th class="px-4 py-2 text-xl"></th>
                        <th class="px-4 py-2 text-xl"></th>
                    </tr>
                </thead>
                <tbody class="overflow-hidden">
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td class="border px-4 py-2">
                            <a asp-action="DetailBooking" asp-route-Id="@item.Id" class="underline text-lg">0</a>
                        </td>
                        <td class="border px-4 py-2">@item.Id</td>
                        <td class="border px-4 py-2">@item.Name</td>
                        <td class="border px-4 py-2">@item.Email</td>
                        <td class="border px-4 py-2">
                            <a asp-action="UpdateBooking" asp-route-Id="@item.Id"  class="underline text-lg">edit</a>
                        </td>
                        <td class="border px-4 py-2">
                            <a asp-action="DeleteBooking" asp-route-Id="@item.Id" class="underline text-lg">delete</a>
                        </td>
                    </tr>    
                    }
                </tbody>
            </table>
        }
        else
        {
           <h1 class="font-serif text-2xl pb-4 pb-10 underline text-center text-red-600">No Appointments</h1> 
        }
    </div>

Views/Appointment/UpdateBooking.cshtml
@model DentistApp.Models.Appointment;

@{
    ViewData["Title"] = "Update-Booking";
}

 <div class="aboutbg px-8">
        <h1 class="text-center font-serif text-3xl md:text-4xl pb-4 text-white">Book Updating</h1>

    </div>
    <div class="container mx-auto max-w-3xl py-20 px-8">
        <h1 class="font-serif text-xl pb-4 underline">
            <a asp-controller="Appointment" asp-action="Main">Return to Home</a>
        </h1>
        <form asp-controller="Appointment" asp-action="UpdateBooking" method="post" class="mx-auto">
            <div class="text-red-600" asp-validation-summary="ModelOnly"></div>
            <div class="py-2 grid grid-cols-1 md:grid-cols-2 gap-5">
                <div class="flex flex-col">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" type="text" class="w-full py-2 px-3 border-2 border-gray-700" />
                    <span asp-validation-for="Name" class="text-red-600"></span>
                </div>
                <div class="flex flex-col">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" type="text" class="py-2 px-3 border-2 border-gray-700"/>
                    <span asp-validation-for="Email" class="text-red-600"></span>
                </div>
            </div>
            <div class="py-2 grid grid-cols-1 md:grid-cols-2 gap-5">
                <div class="flex flex-col">
                    <label asp-for="Age"></label>
                    <input asp-for="Age" type="number" class="py-2 px-3 border-2 border-gray-700 w-full" />
                    <span asp-validation-for="Age" class="text-red-600"></span>
                </div>
                <div class="flex flex-col">
                    <label asp-for="Date"></label>
                    <input asp-for="Date" type="datetime" class="py-2 px-3 border-2 border-gray-700 w-full"/>
                    <span asp-validation-for="Date" class="text-red-600"></span>
                </div>
            </div>
            <div class="">
                <label asp-for="Issue"></label>
               <textarea asp-for="Issue" cols="30" rows="5" class="py-2 px-3 border-2 border-gray-700 w-full"></textarea>
                <span asp-validation-for="Issue" class="text-red-600"></span>
            </div>
            <button type="submit" class="py-2 md:py-3 px-20 bg-red-600 text-white">Update Booking</button>
        </form>
    </div>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" /> }
}